### ISSUE TITLE
No ETA is shown

### ISSUE THREAD

**Issue by dbpalan** [miklcct/kmb-lwb-combined-headway-eta#1]
Using demo site with below URL, stops information shows correctly but no ETA is shown.

http://kmb_eta.csproject.org/?stop=KW16-E-0900-0&selections=74X-1

**Comment by miklcct** [comment]
The API endpoint used, which is the same one as KMB website, no longer works now.

**Comment by miklcct** [comment]
fixed in 1.6.0
