### ISSUE TITLE
All queries will be redirected to proxy server when running in HTTPS server

### ISSUE THREAD

**Issue by dbpalan** [miklcct/kmb-lwb-combined-headway-eta#2]
When running the script in HTTPS server, all queries to search.kmb.hk will be redirected to proxy server.  Since the proxy server redirect all traffic to etav3.kmb.hk, queries to proxy server for search.kmb.hk will be failed.

It looks like the issue is due to determination to call proxy server or not is by checking the protocol of the URL:

Common.js
`        $.get((location.protocol === 'https:' ? Common.PROXY_URL : '') + Common.API_ENDPOINT, query, callback);`

**Comment by miklcct** [comment]
search.kmb.hk is in the whitelist of the proxy server therefore the call should work. This is done because of a limitation not able to AJAX http endpoints from https website.
