### ISSUE TITLE
Seems map would provide performance boost

### ISSUE THREAD

**Issue by winstonma** [miklcct/kmb-lwb-combined-headway-eta#3]
Hi, I decided to use your fetcher code for my [MMM-HK-KMB](https://github.com/winstonma/MMM-HK-KMB) project.

In the [StopRoute.js](https://github.com/miklcct/kmb-lwb-combined-headway-eta/blob/master/scripts/StopRoute.js) there are some `forEach`. Use `map` would improve the performance of the code.

I didn't check the side-effect but it seems to me that it works. I also didn't check other code because `StopRoute` is more critical.

**Comment by miklcct** [comment]
`forEach` and `map` serve different purposes. `forEach` is to run something over items of an array without returning it but `map` is to transform an array into another array using a formula. The code uses both `map` and `forEach` in order to get the desired functionality.

**Comment by winstonma** [comment]
Yes you are right. `map` as this is not the most critical one.

It seems to me that the StopRoute query time is very long (I have no idea but KMB API response time varies). So if the fetching is in sequence (and also there are a lot of bus is running through the stop) would causes long waiting time. And I am not sure if that can be fixed.

I agree this is not a bug, it is just a nice to have.
