### ISSUE TITLE
Date object would subject to the timezone of the server

### ISSUE THREAD

**Issue by winstonma** [miklcct/kmb-lwb-combined-headway-eta#4]
I copied the snippet from [Eta.js](https://github.com/miklcct/kmb-lwb-combined-headway-eta/blob/master/scripts/Eta.js)

```
const time = new Date();
time.setHours(Number(obj.time.split(':')[0]), Number(obj.time.split(':')[1]), 0);
if (time.getTime() - Date.now() < -60 * 60 * 1000 * 2) {
    // the time is less than 2 hours past - assume midnight rollover
    time.setDate(time.getDate() + 1);
}
if (time.getTime() - Date.now() > 60 * 60 * 1000 * 6) {
    // the time is more than 6 hours in the future - assume midnight rollover
    time.setDate(time.getDate() - 1);
}
```

The `time` and `Date.now()` object uses the timezone of the system (I am just using UTC as the system default). However the `setHours` uses the Hong Kong time (obtained from the API). For my case midnight rollover would always happen.

I don't use date but just notice my date is always off by a day when I check the `eta.time` string.

**Comment by miklcct** [comment]
This module is not designed to be run outside Hong Kong Time. Feel free to open a pull request and document the behaviour if you run it outside Hong Kong Time.

**Comment by winstonma** [comment]
Seems this works but really need to check

```
const time = new Date();
const localTime = new Date(time.toLocaleString("en-GB", { timeZone: "Asia/Hong_Kong", hour12: false }));
const tzDiff = time.getTime() - localTime.getTime();
time.setHours(Number(obj.time.split(':')[0]), Number(obj.time.split(':')[1]), 0);
//if (time.getTime() - Date.now() < -60 * 60 * 1000 * 2) {
if (time.getTime() - Date.now() + tzDiff < -60 * 60 * 1000 * 2) {
    // the time is less than 2 hours past - assume midnight rollover
    time.setDate(time.getDate() + 1);
}
//if (time.getTime() - Date.now() > 60 * 60 * 1000 * 6) {
if (time.getTime() - Date.now() + tzDiff > 60 * 60 * 1000 * 6) {
    // the time is more than 6 hours in the future - assume midnight rollover
    time.setDate(time.getDate() - 1);
}
```

It would be better if the modification is done inside `setHours` but it involves the modification of UI (as the `ui.js` assumes server is Hong Kong time).

As it is possible that [ui.js](https://github.com/miklcct/kmb-lwb-combined-headway-eta/blob/master/scripts/ui.js) and [Eta.js](https://github.com/miklcct/kmb-lwb-combined-headway-eta/blob/master/scripts/Eta.js) are running in different timezone. Another possible way is pass the time in API to the `ui.js` and let UI do it's time manipulation.
